### PR TITLE
[RSDK-7336] Update board interface

### PR DESCRIPTION
**Pull request by penguinland**
We've been making some changes to the board interface, and don't want this module to fall behind!
- These boards don't have any analog readers or writers built in. We used to pretend to support analogs by plugging in an MCP3008 to the SPI bus, but now that there is a standalone MCP3008 modular component, you should use that instead and just have this component support the hardware already built into the board. 
    - I've searched Mongo for configs using this board: none of them were using analogs, so this is changing an unused feature.
- Without analogs, this component is `TriviallyReconfigurable` and `TriviallyValidateConfig`.
- Rename `AnalogReaderByName` -> `AnalogByName` and `AnalogReaderNames` -> `AnalogNames`
- `DigitalInterruptByName` returns an error, rather than a boolean indicating whether it succeeded.
- Status-reporting is gone.
- `StreamTicks` exists for digital interrupts (though this specific board just returns an `UnimplementedError`).

Needs more testing on real hardware, but in the meantime I could use more eyeballs on the changes.

### CODE REVIEW

**Comment by martha-johnston** [comment]
I'm a bit confused why so much relating to analogs needs to be removed. Maybe it's reasoning specific to periph that I'm not familiar with? I see your point about how the there's already an MCP3008 modular component, but wouldn't this board still need to support analogs to read those values? like the pi code does for example. it also assumes the analog readers are MCP3008 in the config and supports reading them and keeping track of them with `AnalogByName` and by storing `analogReaders` on the board struct.

**Comment by penguinland** [comment]
> why... analogs needs to be removed

It's a separate effort Rand and I discussed. The [general goal](https://viam.atlassian.net/browse/RSDK-7091) is that only boards with built-in analog readers (like the Beaglebone, or the microcontrollers the microRDK team uses) would implement analog readers. Any robot that wires in an MCP3008 would instead use [the MCP300x component](https://github.com/mestcihazal/mcp3004-8-go/tree/main). We're still laying the groundwork for doing this across all boards built into the RDK, but for standalone ones in viam-labs (especially ones so infrequently used), we're just pushing ahead with it because they don't have as much scrutiny.

> wouldn't this board still need to support analogs to read those values?

_Something_ would need to support it, but Hazal's modular component I linked would do that. It implements a sensor component, and when you `GetReadings` from it, it reads the analogs.

**Comment by martha-johnston** [comment]
ah got it thanks for explaining, the context about wanting to move towards not relying on MCP300x in boards is helpful, I guess this is just the first time I'm seeing it.

**Review by biotinker — APPROVED** [review]
LGTM

**Review by martha-johnston — APPROVED** [review]
lgtm assuming hardware tests go well

**Comment by penguinland** [comment]
Tried on an orange pi zero2: everything starts up fine. There are errors getting and setting actual pins (the periph library expects something different in `/sys/class/gpio`, I think?) but the parts that changed in this PR (the board interface itself) work great.

**Comment by penguinland** [comment]
I've also uploaded the module to the registry as version 0.1.2 (previous was 0.1.1).

**Pull request merged**
