### PR TITLE
[RSDK-5776] Remove ownership of SPI and I2C buses

### PR DESCRIPTION
**Pull request by penguinland**
This change is half the size it appears: most of it is automated stuff in go.mod and go.sum.

A [recent epic](https://viam.atlassian.net/browse/RSDK-4806) got all components that use the I2C and SPI buses to talk to those buses directly instead of going through the board components. This PR updates the periph board to keep parity with the boards in the RDK. Also, other parts of the board interface have changed, so this PR also updates those: the logger has moved from Eric's personal github into RDK itself, the analog reader got its own package, and the board interface has a new function for analog writers.

Everything still compiles, but I haven't tried it more thoroughly than that yet. but I will before merging.

### CODE REVIEW

**Review by mcvella — APPROVED** [review]
lgtm as far as I can tell, have not tested

**Comment by penguinland** [comment]
Tried on a Jetson Orin: works fine, except that status reporting on a modular board is broken. This is not an issue with this module: _all_ modular boards will report their statuses incorrectly because of a stale cache in the RDK which never contacts the module to refresh itself. The issue is reported to the netcode team: Dan G confirms that it's a bug on their end, and they're looking into fixing it.

**Comment by penguinland** [comment]
(also, I tried out the analog readers in here, and they work fine, too)

**Comment by penguinland** [comment]
Jira ticket for the caching issue: https://viam.atlassian.net/browse/RSDK-6216

**Comment by penguinland** [comment]
uploaded to the registry: things continue to work! The latest version is now 0.1.1 (I bumped the minor version because this is a pretty big change, and then bumped the patch version because 0.1.0 printed lots of debugging info I forgot to remove before uploading)

**Pull request merged**
